import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import { endpoints } from './api';

const icons = ['⚒', '✚', '▣', '▤', '♥', '⇄'];
const colors = ['mint', 'blue', 'yellow', 'orange', 'pink', 'slate'];
const labels = { RECEBIDA: 'Recebida', EM_ANALISE: 'Em análise', EM_ANDAMENTO: 'Em andamento', RESOLVIDA: 'Resolvida', INDEFERIDA: 'Indeferida', CANCELADA: 'Cancelada' };

function useSession() {
  const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('carpinaon_user')) || null; } catch { return null; } });
  function enter(result) { localStorage.setItem('carpinaon_token', result.token); localStorage.setItem('carpinaon_user', JSON.stringify(result.usuario)); setUser(result.usuario); }
  function leave() { localStorage.removeItem('carpinaon_token'); localStorage.removeItem('carpinaon_user'); setUser(null); }
  return { user, enter, leave };
}

function Auth({ onLogin }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ cpf: '', senha: '', nome: '', email: '', telefone: '' });
  const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const update = (key) => (e) => setForm((value) => ({ ...value, [key]: e.target.value }));
  async function submit(e) { e.preventDefault(); setMessage(''); setLoading(true); try { if (mode === 'login') onLogin(await endpoints.login({ cpf: form.cpf, senha: form.senha })); else { await endpoints.register(form); setMode('login'); setMessage('Cadastro feito. Entre com seu CPF e senha.'); } } catch (err) { setMessage(err.message); } finally { setLoading(false); } }
  return <main className="auth"><div className="auth-card"><div className="brand-mark">⌂</div><h1>CarpinaON</h1><p className="muted">Serviços públicos de Carpina</p><div className="tabs"><button className={mode === 'login' ? 'selected' : ''} onClick={() => setMode('login')}>Entrar</button><button className={mode === 'register' ? 'selected' : ''} onClick={() => setMode('register')}>Criar conta</button></div>{message && <div className="alert">{message}</div>}<form onSubmit={submit}>{mode === 'register' && <><label>Nome completo<input value={form.nome} onChange={update('nome')} required /></label><label>E-mail<input type="email" value={form.email} onChange={update('email')} required /></label><label>Telefone<input value={form.telefone} onChange={update('telefone')} /></label></>}<label>CPF<input value={form.cpf} onChange={update('cpf')} required /></label><label>Senha<input type="password" value={form.senha} onChange={update('senha')} required /></label><button className="primary full" disabled={loading}>{loading ? 'Aguarde...' : mode === 'login' ? 'Entrar no portal' : 'Criar minha conta'}</button></form></div></main>;
}

function Header({ page, setPage, user, logout, unread }) { const links = [['home', 'Início'], ['requests', 'Meus pedidos'], ['notifications', 'Avisos'], ['events', 'Turismo']]; return <header><button className="logo" onClick={() => setPage('home')}><span>⌂</span> CarpinaON</button><nav>{links.map(([id, text]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}>{text}{id === 'notifications' && unread > 0 && <b>{unread}</b>}</button>)}</nav><div className="account">Olá, {user?.nome?.split(' ')[0]} <button onClick={logout}>Sair</button></div></header>; }

function Home({ categories, services, openRequest }) { return <section className="page"><div className="hero"><div><p className="eyebrow">PORTAL MUNICIPAL</p><h2>Como podemos ajudar?</h2><p>Encontre serviços da Prefeitura de Carpina em um só lugar.</p></div><button className="accent" onClick={() => openRequest()}>+ Nova solicitação</button></div><h3>Categorias de serviços</h3><div className="grid">{categories.map((category, index) => <button className="category" key={category.id} onClick={() => openRequest(category.id)}><span className={`category-icon ${colors[index % colors.length]}`}>{icons[index % icons.length]}</span><div><strong>{category.nome}</strong><small>{services.filter((service) => service.categoria?.id === category.id).length} serviços disponíveis</small><p>{category.descricao || 'Serviços públicos municipais.'}</p></div></button>)}</div>{!categories.length && <Empty text="Nenhuma categoria encontrada." />}</section>; }

function Requests({ requests, openRequest, showDetail }) { return <section className="page"><div className="section-head"><div><h2>Meus pedidos</h2><p>Acompanhe suas solicitações à Prefeitura.</p></div><button className="accent" onClick={() => openRequest()}>+ Nova solicitação</button></div>{requests.length ? <div className="requests">{requests.map((item) => <button className="request" key={item.id} onClick={() => showDetail(item.protocolo)}><div className="request-top"><strong>{item.protocolo}</strong><Status status={item.status} /></div><b>{item.servico?.nome}</b><p>{item.descricao}</p><small>Enviado em {date(item.createdAt)} · Ver detalhes</small></button>)}</div> : <Empty text="Você ainda não abriu nenhuma solicitação." action={openRequest} />}</section>; }

function Status({ status }) { return <span className={`status ${status}`}>{labels[status] || status}</span>; }
function date(value) { return value ? new Date(value).toLocaleDateString('pt-BR') : ''; }
function Empty({ text, action }) { return <div className="empty"><div>□</div><p>{text}</p>{action && <button className="primary" onClick={() => action()}>Abrir solicitação</button>}</div>; }

function NewRequest({ services, selectedCategory, onBack, onCreated }) { const choices = selectedCategory ? services.filter((item) => item.categoria?.id === selectedCategory) : services; const [form, setForm] = useState({ service: '', cep: '', complemento: '', pontoReferencia: '', descricao: '' }); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const update = (key) => (e) => setForm((value) => ({ ...value, [key]: e.target.value })); async function submit(e) { e.preventDefault(); setSaving(true); setMessage(''); try { const created = await endpoints.createRequest({ servicoIds: [Number(form.service)], cep: form.cep, complemento: form.complemento, pontoReferencia: form.pontoReferencia, descricao: form.descricao }); onCreated(created); } catch (err) { setMessage(err.message); } finally { setSaving(false); } } return <section className="page narrow"><div className="section-head"><div><h2>Nova solicitação</h2><p>Preencha os dados para abrir um protocolo.</p></div><button className="outline" onClick={onBack}>Voltar</button></div>{message && <div className="alert">{message}</div>}<form className="panel" onSubmit={submit}><label>Serviço<select value={form.service} onChange={update('service')} required><option value="">Selecione um serviço</option>{choices.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label>CEP<input value={form.cep} onChange={update('cep')} required /></label><label>Complemento <em>(opcional)</em><input value={form.complemento} onChange={update('complemento')} /></label><label>Ponto de referência <em>(opcional)</em><input value={form.pontoReferencia} onChange={update('pontoReferencia')} /></label><label>Descrição<textarea value={form.descricao} onChange={update('descricao')} required placeholder="Conte os detalhes da sua solicitação..." /></label><button className="primary" disabled={saving || !form.service}>{saving ? 'Enviando...' : 'Enviar solicitação'}</button></form></section>; }

function Notifications({ items, reload }) { async function mark(item) { if (!item.lida) { await endpoints.markRead(item.id); reload(); } } return <section className="page"><h2>Avisos</h2><p className="intro">Atualizações dos seus pedidos e comunicados importantes.</p><div className="panel notifications">{items.length ? items.map((item) => <button className={item.lida ? 'notification' : 'notification unread'} key={item.id} onClick={() => mark(item)}><span>{!item.lida ? '●' : '○'}</span><div><strong>{item.titulo}</strong><p>{item.mensagem}</p><small>{date(item.createdAt)}</small></div></button>) : <Empty text="Você não tem avisos ainda." />}</div></section>; }

function Events({ events }) { return <section className="page"><h2>Descubra Carpina</h2><p className="intro">Pontos turísticos, cultura e eventos da nossa cidade.</p><div className="grid events">{events.map((event) => <article className="event" key={event.id}>{event.imagemUrl ? <img src={event.imagemUrl} alt="" /> : <div className="event-placeholder">Carpina</div>}<div><small>{event.categoria || 'Turismo'}</small><h3>{event.titulo}</h3><p>{event.descricao}</p><span>⌖ {event.local || 'Carpina - PE'}</span>{event.rating && <b>★ {event.rating}</b>}</div></article>)}</div>{!events.length && <Empty text="Nenhum evento encontrado." />}</section>; }

function Detail({ detail, close }) { return <div className="modal-bg" onClick={close}><div className="modal" onClick={(e) => e.stopPropagation()}><div className="modal-head"><div><strong>{detail.protocolo}</strong><Status status={detail.status} /></div><button onClick={close}>×</button></div><p><b>{detail.servico?.nome}</b></p><p>{detail.descricao}</p><hr /><h3>Histórico</h3>{detail.historico?.map((item) => <div className="history" key={item.id}><b>{labels[item.statusNovo] || item.statusNovo}</b><small>{date(item.changedAt)}</small>{item.observacao && <p>{item.observacao}</p>}</div>)}<button className="outline" onClick={close}>Fechar</button></div></div>; }

function App() { const session = useSession(); const [page, setPage] = useState('home'); const [categories, setCategories] = useState([]); const [services, setServices] = useState([]); const [requests, setRequests] = useState([]); const [notifications, setNotifications] = useState([]); const [events, setEvents] = useState([]); const [detail, setDetail] = useState(null); const [requestCategory, setRequestCategory] = useState(null); const [created, setCreated] = useState(null); const [error, setError] = useState('');
  async function load() { try { const [cats, svcs, reqs, notes, evts] = await Promise.all([endpoints.categories(), endpoints.services(), endpoints.requests(), endpoints.notifications(), endpoints.events()]); setCategories(cats || []); setServices(svcs || []); setRequests(reqs || []); setNotifications(notes || []); setEvents(evts || []); } catch (err) { setError(err.message); } }
  useEffect(() => { if (session.user) load(); }, [session.user]);
  const unread = useMemo(() => notifications.filter((item) => !item.lida).length, [notifications]);
  if (!session.user) return <Auth onLogin={session.enter} />;
  if (created) return <><Header page="requests" setPage={setPage} user={session.user} logout={session.leave} unread={unread} /><section className="page success-page"><div className="success">✓<h2>Solicitação enviada!</h2><p>Seu protocolo foi registrado com sucesso.</p><strong>{created.protocolo}</strong><button className="primary" onClick={() => { setCreated(null); setPage('requests'); load(); }}>Ver meus pedidos</button></div></section></>;
  let content = page === 'home' ? <Home categories={categories} services={services} openRequest={(id) => { setRequestCategory(id || null); setPage('new'); }} /> : page === 'requests' ? <Requests requests={requests} openRequest={(id) => { setRequestCategory(id || null); setPage('new'); }} showDetail={async (protocol) => { try { setDetail(await endpoints.requestDetail(protocol)); } catch (err) { setError(err.message); } }} /> : page === 'new' ? <NewRequest services={services} selectedCategory={requestCategory} onBack={() => setPage('home')} onCreated={setCreated} /> : page === 'notifications' ? <Notifications items={notifications} reload={load} /> : <Events events={events} />;
  return <><Header page={page} setPage={setPage} user={session.user} logout={session.leave} unread={unread} />{error && <div className="global-error">{error}<button onClick={() => setError('')}>×</button></div>}{content}{detail && <Detail detail={detail} close={() => setDetail(null)} />}</>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
